name: Build installer

on:
  push:
    branches:
      - installer

jobs:
  windows:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest, ubuntu-20.04]

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build installer
      run: |
        pyinstaller --onefile installer.py
        pyinstaller --onefile installer-gitee.py

    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: Installer-${{ matrix.os }}
        path: dist
